# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6a87370dd7bc922ce7c8466d2391adfcdce4c05a51ad7055e979a4114663ec99723b0a05997d3b5642a38f1e8ac94b0c98d007556bc5b798dea2143a5fde11

test:
  secret_key_base: fa401e66d05165f5efb4197b3ec83174693171725920bc179d1e47f72c2191504c91021454b09bc96ee5e7acbba5b8c35dd86782bb724938b77fb02a8bc9c791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
